IDENTIFICATION DIVISION.
PROGRAM-ID.PAYROLL.
AUTHOR.YOUR NAME.
ENVIRONMENT DIVISION.
INPUT-OUTPUT SECTION.
FILE-CONTROL.
    SELECT EMPLOYEE-FILE ASSIGN TO 'employee.dat'
       ORGANIZATION IS INDEXED
       ACCESS MODE IS RANDOM
       RECORD KEY IS EMPLOYEE-ID.
    SELECT PAYSLIP-FILE ASSIGN TO 'payslip.txt'
       ORGANIZATION IS LINE SEQUENTIAL.

DATA DIVISION.
FILE SECTION.
FD EMPLOYEE-FILE
01 EMPLOYEE-RECORD.
    05 EMPLOYEE-ID       PIC X(10).
    05 EMPLOYEE-NAME     PIC X(3)V99.
    05 HOURS-WORKED      PIC X(3)V99.
    05 HOURLY-RATE       PIC X(3)V99.
    05 OVERTIME-HOURS    PIC X(3)V99.
    05 TAX DEDUCTIONS    PIC X(3)V99.
    05 BENEFITS          PIC X(3)V99.
    05 LEAVE-DEDUCTIONS  PIC X(3)V99.
    05 NET-SALARY        PIC X(3)V99.

FD PAYSLIP-FILE.
01 PAYSLIP-RECORD        PIC 9(7)V99.

WORKING-STORAGE SECTION.
01 WS-TOTAL-STORAGE      PIC 9(7)V99.
01 WS-OVERTIME-PAY       PIC 9(5)V99.
01 WS-GROSS-SALARY       PIC 9(7)V99.

PROCEDURE DIVISION.
MAIN-PROCEDURE.
    OPEN INPUT EMPLOYEE-FILE.
    OPEN OUTPUT PAYSLIP-FILE.
    PERFORM PROCESS-EMPLOYEES.
    CLOSE EMPLOYEE-FILE.
    CLOSE PAYSLIP-FILE.
    STOP RUN.

PROCESS-EMPLOYEES.
    READ EMPLOYEE-FILE INTO EMPLOYEE-RECORD
         AT END MOVE 'NO' TO WS-EOF
        NOT AT END PERFORM CALCULATE-SALARY
                   PERFORM GENERATE-PAYSLIP
                   GO TO PROCESS-EMPLOYEES.

CALCULATE-SALARY.
    COMPUTE WS